server:
  port: 8080 # Indicate the PORT where this service will be started

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_ENUMS_USING_TO_STRING: true
      indent_output: true
    deserialization:
      READ_ENUMS_USING_TO_STRING: true

management:
  endpoints:
    web:
      base-path: "/api/k8sclient/v1/"
      exposure:
        include: "health, info, metrics"
      path-mapping:
        health: "healthCheck"
        info: "info"
        metrics: "metrics"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: "always"

k8s:
#  endpoint: ${KUBERNETES_MASTER:localhost:8080}
  endpoint: https://192.168.112.128:6443
  defaultNamespace: default

jwt:
  secret: sad87s6dkjaehdfi7eyfa
  ttl: 1h
